export const schoolList = [
    { id: 'stem-6th-of-october', name: 'STEM 6th of October' },
    { id: 'stem-el-obour', name: 'STEM El Obour' },
    { id: 'stem-dakahlia', name: 'STEM Dakahlia' },
    { id: 'stem-alexandria', name: 'STEM Alexandria' },
    { id: 'stem-assiut', name: 'STEM Assiut' },
    { id: 'stem-kafr-elsheikh', name: 'STEM Kafr El-Sheikh' },
    { id: 'stem-ismailia', name: 'STEM Ismailia' },
    { id: 'stem-luxor', name: 'STEM Luxor' },
    { id: 'stem-red-sea', name: 'STEM Red Sea' },
    { id: 'stem-gharbia', name: 'STEM Gharbia' },
    { id: 'stem-monufia', name: 'STEM Monufia' },
    { id: 'stem-qena', name: 'STEM Qena' },
    { id: 'stem-sharqia', name: 'STEM Sharqia' },
    { id: 'stem-beni-suef', name: 'STEM Beni Suef' },
    { id: 'stem-minya', name: 'STEM Minya' },
    { id: 'stem-sohag', name: 'STEM Sohag' },
    { id: 'stem-fayoum', name: 'STEM Fayoum' },
    { id: 'stem-qalyubia', name: 'STEM Qalyubia' },
    { id: 'stem-aswan', name: 'STEM Aswan' },
    { id: 'stem-new-valley', name: 'STEM New Valley' },
];
